Project 3<br> Sean Javiya<br> Jake Wong<br> Timothy Jan<br>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score

pd.options.mode.chained_assignment = None  # default='warn'

Experiment 1

In [2]:
data = pd.read_csv('bank-additional/bank-additional-full.csv', delimiter=';')
data.head(5)

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

Experiment 2

In [3]:
train, test = train_test_split(data, test_size=0.1, train_size=0.9, random_state=(2021-10-25), shuffle=True, stratify=None)
test = test.drop(columns='duration')
train = train.drop(columns='duration')


Experiment 3

In [4]:
y_test = test.pop('y')
y_train = train.pop('y')

categorical_test_data = test.iloc[:, :7]
categorical_train_data = train.iloc[:, :7]

Experiment 4

In [5]:
test_df = pd.get_dummies(categorical_test_data, drop_first=True) 
train_df = pd.get_dummies(categorical_train_data, drop_first=True)

Experiment 5

In [6]:
nbfit = CategoricalNB()
nbfit.fit(train_df, y_train)
nb_prediction = nbfit.predict(test_df)
#print(nb_prediction.len)
#print(y_test)
testscore = 0
for index, value in enumerate(y_test):
    if value == nb_prediction[index]:
        testscore += 1
#print(testscore/len(y_test))
percentage_score = testscore/len(y_test)
print("test percentage correct: ", percentage_score)

nb_train_prediction = nbfit.predict(train_df)
trainscore = 0
for index, value in enumerate(y_train):
    if value == nb_train_prediction[index]:
        trainscore += 1
#print(trainscore/len(y_train))
percentage_train_score = trainscore/len(y_train) 
print("train percentage correct: ", percentage_train_score)


test percentage correct:  0.8788540907987376
train percentage correct:  0.8818689470986538


Experiment 6

In [7]:
#print(data.age)
unique_ages = len(set(data.age))
print("There are ", unique_ages, " categories for age in the entire data.  This is unreasonable.")
# should we do train and test age too?

There are  78  categories for age in the entire data.  This is unreasonable.


Experiment 7

In [8]:
#for i in range(len(categorical_test_data)):
#    match int(int(categorical_test_data.age[i:i+1])/10):
#        case 1:
#            categorical_test_data.age[i:i+1] == 'teen'
#        case 2:
#            categorical_test_data.age[i:i+1] == 'twenty'

#    if int(int(categorical_test_data.age[i:i+1])/10) == 1
#        categorical_test_data.age[i:i+1] == 'teen'

age_dict = {1:"tens",2:"twenties",3:"thirties",4:"forties",5:"fifties",6:"sixties",7:"seventies",8:"eighties",9:"nineties"}
for ind in categorical_test_data.index:
    decade_value = int(categorical_test_data['age'][ind]/10)
    categorical_test_data['age'][ind] = age_dict[decade_value]
for ind in categorical_train_data.index:
    decade_value = int(categorical_train_data['age'][ind]/10)
    categorical_train_data['age'][ind] = age_dict[decade_value]
test_df_generations = pd.get_dummies(categorical_test_data, drop_first=True)
train_df_generations = pd.get_dummies(categorical_train_data, drop_first=True)

test_df_generations['age_nineties'] = 0 #preprocessing to add column of 0's for equal number of columns

In [9]:
nbfit_generations = CategoricalNB()
nbfit_generations.fit(train_df_generations, y_train)
nb_prediction_generations = nbfit_generations.predict(test_df_generations)

testscore = 0
for index, value in enumerate(y_test):
    if value == nb_prediction_generations[index]:
        testscore += 1

percentage_score_generations = testscore/len(y_test)
print("test percentage correct: ", percentage_score_generations)

nb_train_prediction_generations = nbfit_generations.predict(train_df_generations)
trainscore = 0
for index, value in enumerate(y_train):
    if value == nb_train_prediction_generations[index]:
        trainscore += 1

percentage_train_score_generations = trainscore/len(y_train) 
print("train percentage correct: ", percentage_train_score_generations)


test percentage correct:  0.6448167030832727
train percentage correct:  0.8808168550540884


Experiment 8

In [10]:
categorical_test_data_knn = test.iloc[:, :7]
categorical_train_data_knn = train.iloc[:, :7]
test_df_knn = pd.get_dummies(categorical_test_data_knn, drop_first=True) 
train_df_knn = pd.get_dummies(categorical_train_data_knn, drop_first=True)
KNNfit = KNeighborsClassifier()
KNNfit.fit(train_df_knn, y_train)
kn_prediction = KNNfit.predict(test_df_knn)
testscore = 0
for index, value in enumerate(y_test):
    if value == kn_prediction[index]:
        testscore += 1
percentage_score_knn = testscore/len(y_test)
print("test percentage correct: ", percentage_score_knn)

kn_train_prediction = KNNfit.predict(train_df_knn)
trainscore = 0
for index, value in enumerate(y_train):
    if value == kn_train_prediction[index]:
        trainscore += 1

percentage_train_score_knn = trainscore/len(y_train) 
print("train percentage correct: ", percentage_train_score_knn)

test percentage correct:  0.8771546491866958
train percentage correct:  0.8903935903315439


Experiment 9

In [11]:
counts = y_test.value_counts().to_dict()
print(counts)
testscore = 0
for index in range(len(kn_prediction)):
    if kn_prediction[index] == 'no':
        testscore += 1

percentage_score_knn = testscore/len(y_test)
print("test percentage correct if we assume there are no subscribed customers: ", percentage_score_knn)

testscore = 0
for index in range(len(kn_train_prediction)):
    if kn_train_prediction[index] == 'no':
        testscore += 1

percentage_score_knn_train = testscore/len(y_train)
print("train percentage correct if we assume there are no subscribed customers: ", percentage_score_knn_train)

{'no': 3646, 'yes': 473}
test percentage correct if we assume there are no subscribed customers:  0.965768390386016
train percentage correct if we assume there are no subscribed customers:  0.9718363052685532


Experiment 10

In [12]:
#zeros like output of ^ 
zeros_dumb = pd.DataFrame(np.zeros_like(kn_train_prediction))
y_train_binary = pd.DataFrame(np.where(y_train.values == 'yes', 1, 0),y_train.index)
nos_like = pd.DataFrame(np.where(y_train.values == 'yes', 'no', 'no'),y_train.index)
ConfusionMatrix_Dumb = confusion_matrix(y_true= y_train, y_pred= nos_like)
RocAuc_score = roc_auc_score(y_train_binary, zeros_dumb)
print("When assuming no customers are subscribed, we can compare to the actual training data to \n"
      "create the confusion matrix: \n"
      , ConfusionMatrix_Dumb,
      "\nand its AUC is:\n"
      , RocAuc_score)

When assuming no customers are subscribed, we can compare to the actual training data to 
create the confusion matrix: 
 [[32902     0]
 [ 4167     0]] 
and its AUC is:
 0.5


Experiment 11

In [13]:
nb_train_predictions_generations_binary = pd.DataFrame(np.where(pd.DataFrame(nb_train_prediction_generations).values == 'yes', 1, 0),pd.DataFrame(nb_train_prediction_generations).index)
ConfusionMatrix_generations = confusion_matrix(y_true= y_train, y_pred= nb_train_prediction_generations)
RocAuc_score_generations = roc_auc_score(y_train_binary, nb_train_predictions_generations_binary)
print("When using the generations model from Experiment 7, we can compare to the actual training data to \n"
      "create the confusion matrix: \n"
      , ConfusionMatrix_generations,
      "\nand its AUC is:\n"
      , RocAuc_score_generations)

kn_train_prediction_binary = pd.DataFrame(np.where(pd.DataFrame(kn_train_prediction).values == 'yes', 1, 0),pd.DataFrame(kn_train_prediction).index)
ConfusionMatrix_kn = confusion_matrix(y_true= y_train, y_pred= kn_train_prediction)
RocAuc_score_kn = roc_auc_score(y_train_binary, kn_train_prediction_binary)
print("\n\nWhen using the KNN model from Experiment 8, we can compare to the actual training data to \n"
      "create the confusion matrix: \n"
      , ConfusionMatrix_kn,
      "\nand its AUC is:\n"
      , RocAuc_score_kn)


When using the generations model from Experiment 7, we can compare to the actual training data to 
create the confusion matrix: 
 [[32219   683]
 [ 3735   432]] 
and its AUC is:
 0.5414565448830108


When using the KNN model from Experiment 8, we can compare to the actual training data to 
create the confusion matrix: 
 [[32432   470]
 [ 3593   574]] 
and its AUC is:
 0.5617320670877847


Experiment 12

In [44]:
train_add_y = pd.concat([train_df, y_train], axis= 1)

yes_data = train_add_y.where(cond= train_add_y.y=='yes')
yes_data = yes_data.dropna(axis= 0, how= 'all')
# yes_data #8.88 x less than data
over_sample = yes_data.sample(frac=1, random_state=(2021-10-25))
over_sample_part = yes_data.sample(frac=0.88, random_state=(2021-10-25))
balanced_train = train_add_y
for i in range(6):
    balanced_train = balanced_train.append(over_sample)
balanced_train = balanced_train.append(over_sample_part)
counts = balanced_train.y.value_counts().to_dict()
print("Number of yes and no values after balancing the training set:\n", counts)


Number of yes and no values after balancing the training set:
 {'no': 32902, 'yes': 32836}


Experiment 13

In [45]:
y_balanced_train = balanced_train.pop('y')
balanced_train_gen = balanced_train.copy(deep=True)

for ind in balanced_train_gen.index:
    #print(balanced_train_gen['age'][ind])
    if isinstance(balanced_train_gen['age'][ind], pd.Series):
        #print(balanced_train_gen['age'][ind].iloc[0])
        decade_value = (balanced_train_gen['age'][ind].iloc[0])
        if decade_value in age_dict.values():
            decade_value = decade_value
        else:
            decade_value = int(int(decade_value) / 10)
            decade_value = age_dict[decade_value]
    else:
        decade_value = int(balanced_train_gen['age'][ind] / 10)
        decade_value = age_dict[decade_value]
    balanced_train_gen['age'][ind] = decade_value

test_gen = pd.get_dummies(test, drop_first=True)
balanced_train_gen = pd.get_dummies(balanced_train_gen, drop_first=True)

test_gen['age_nineties'] = 0 #preprocessing to add column of 0's for equal number of columns


nbfit_balanced_gen = CategoricalNB()
nbfit_balanced_gen.fit(balanced_train_gen, y_balanced_train)
nb_predict_balanced_gen = nbfit_balanced_gen.predict(balanced_train_gen)
nb_predict_balanced_gen_test = nbfit_balanced_gen.predict(test_df_generations)
print("When balancing the data and then re-training our generation model from Experiment 7:\n")
testscore = 0
for index, value in enumerate(y_test):
    if value == nb_predict_balanced_gen_test[index]:
        testscore += 1

percentage_score_balanced_generations = testscore/len(y_test)
print("test percentage correct: ", percentage_score_balanced_generations)


trainscore = 0
for index, value in enumerate(y_balanced_train):
    if value == nb_predict_balanced_gen[index]:
        trainscore += 1

percentage_train_score_balanced_generations = trainscore/len(y_balanced_train) 
print("train percentage correct: ", percentage_train_score_balanced_generations)

When balancing the data and then re-training our generation model from Experiment 7:

test percentage correct:  0.3046856033017723
train percentage correct:  0.6057835650613039


In [49]:
#categorical_test_data_knn = test.iloc[:, :7]
#categorical_train_data_knn = train.iloc[:, :7]
#test_df_knn = pd.get_dummies(categorical_test_data_knn, drop_first=True) 
#train_df_knn = pd.get_dummies(categorical_train_data_knn, drop_first=True)
#balanced_train

balanced_KNNfit = KNeighborsClassifier()
balanced_KNNfit.fit(balanced_train, y_balanced_train)
balanced_kn_prediction = balanced_KNNfit.predict(test_df_knn)
balanced_kn_train_prediction = balanced_KNNfit.predict(balanced_train)

print("When balancing the data and then re-training our generation model from Experiment 8:\n")
testscore = 0
for index, value in enumerate(y_test):
    if value == balanced_kn_prediction[index]:
        testscore += 1
percentage_score_knn_balanced = testscore/len(y_test)
print("test percentage correct: ", percentage_score_knn_balanced)

trainscore = 0
for index, value in enumerate(y_balanced_train):
    if value == balanced_kn_train_prediction[index]:
        trainscore += 1

percentage_train_score_knn_balanced = trainscore/len(y_balanced_train) 
print("train percentage correct: ", percentage_train_score_knn_balanced)

When balancing the data and then re-training our generation model from Experiment 8:

test percentage correct:  0.6385044913814033
train percentage correct:  0.7686117618424655
